# Generated by Django 2.0.7 on 2018-07-21 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='')),
                ('approval', models.CharField(blank=True, choices=[('APPROVAL PENDING', 'APPROVAL PENDING'), ('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], default='APPROVAL PENDING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('reasons', models.CharField(blank=True, choices=[('SICK LEAVE', 'SICK LEAVE'), ('PERSONAL LEAVE', 'PERSONAL LEAVE'), ('SABBATICAL LEAVE', 'SABBATICAL LEAVE'), ('MATERNITY LEAVE', 'MATERNITY LEAVE')], max_length=100)),
                ('approval', models.CharField(blank=True, choices=[('APPROVAL PENDING', 'APPROVAL PENDING'), ('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], default='APPROVAL PENDING', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
